# Declaration of dictionaries and lists

shop_info = {
	"name" : "tigre",
	"street": "via",
	"working_hours": "2"
}

categories_dict = {
	"Frutta-e-Verdura": [
		"Frutta-Fresca",
		"Frutta-Pronta-da-mangiare",
		"Aglio-Peperoncino-Odori",
		"Funghi-Olive-Capperi",
        "Ortaggi",
        "Verdura-Fresca",
        "Verdura-Lavata-o-Tagliata",
        "Frutta-Secca-Disidratata",
        "Legumi-e-Cereali-secchi",
        "Barrette-Snack-Polpa-frutta",
        "Condimenti-Spezie-Farine",
        "Piatti-Pronti"
    ],
    "Carne-e-Pesce": [
        "Bovino",
        "Ovino-Avicunicolo",
        "Pollo-Tacchino",
        "Speciali",
        "Suino",
        "Frutti-di-Mare",
        "Pesci-Interi-Tranci-Filetti",
        "Pesci-Salati-o-Confezionati",
        "Carne-Pronta",
        "Carne-Pronta-a-Cuocere",
        "Pesce-Cotto",
        "Pesce-Pronto-a-Cuocere",
        "Sushi"
    ],
    "Forno-e-Gastronomia": [
        "Dolci-Pasticceria",
        "Pane-Panini",
        "Pizza-Focacce-Rustici",
        "Taralli-Freselle-Grissini",
        "Pasta-Fresca",
        "Piatti-Pronti",
        "Sughi-Condimenti",
        "Formaggi-Freschissimi",
        "Formaggi-Freschi",
        "Formaggi-Semistagionati",
        "Formaggi-Stagionati",
        "Insaccati",
        "Salumi"
    ],
    "Prodotti-da-Frigo": [
        "Formaggi-Confezionati",
        "Salumi-Confezionati",
        "Latte-Fresco",
        "Latte-uht",
        "Panna-fresca-Burro",
        "Panna-Besciamella-uht",
        "Yogurt",
        "Pasta-Fresca",
        "Uova-Lievito-Sfoglie",
        "Gastronomia",
        "Snack-Merende-Dessert"
    ],
    "Surgelati": [
        "Gelati",
        "Gelati-Vaschetta",
        "Torte-Dessert",
        "Carne-Surgelata",
        "Pesce-Surgelato",
        "Piatti-Sughi-surgelati",
        "Pizze-Dolci-surgelati",
        "Verdura-Surgelata"
    ],
    "Dispensa-Salata": [
        "Conserve-Animali",
        "Conserve-Vegetali",
        "Olive-Sottolio-Sottaceto",
        "Passate-Sughi-Dadi",
        "Sale-Olio-Aceto",
        "Salse-Spezie",
        "Pasta-Riso",
        "Primi-piatti-Zuppe",
        "Alimenti-No-Glutine",
        "Cibi-Etnici",
        "Snack-Salati-Patatine",
        "Sostituti-Pane"
    ],
    "Dispensa-Dolce": [
        "Caffè",
        "Orzo-Solubili",
        "Tè-Infusi-Tisane",
        "Caramelle-Cioccolate",
        "Cereali",
        "Fette-Spalmabili",
        "Pasticcini-Biscotti",
        "Torte-Merendine",
        "Farine-Zucchero-Lievito",
        "Preparazione-Dolci",
        "Dolci-no-Glutine",
        "Sostituti-Pasto-Integratori"
    ],
    "Bevande-e-Bollicine": [
        "Acqua-Preparati",
        "Bibite-gassate",
        "Succhi-Frutta",
        "Tè-Integratori-Energy-drink",
        "Aperitivi",
        "Birre",
        "Spumanti-Champagne",
        "Liquori",
        "Vini-Esteri-Liquorosi",
        "Vini-Tavola",
        "Vini-Bianchi",
        "Vini-Rosati",
        "Vini-Rossi"
    ],
    "Infanzia": [
        "Biscotti-Pastine-Farine",
        "Latte-Infanzia",
        "Liofilizzati-Infusi",
        "Omogeneizzati",
        "Snack-Pouch-Merendine",
        "Cura-Baby",
        "Detergenti-Polveri",
        "Pannolini-Salviette",
        "Biberon-Prime-pappe",
        "Calze-Bimbo",
        "Puericultura-varie"
    ],
    "Cura-Casa": [
        "Ammorbidenti-Additivi",
        "Detersivi-Bucato",
        "Stiro-Guardaroba",
        "Cottura-Conservazione",
        "Monouso-Carta-Casa",
        "Party-Regalo-Pic-Nic",
        "Sapone-Piatti",
        "Accessori-Pulizia-casa",
        "Deo-ambiente-Insetticidi",
        "Detergenti-Casa",
        "Brico-Giardino",
        "Cancelleria"
    ],
    "Cura-Persona-e-Animali": [
        "Epilazione-Rasatura",
        "Igiene-Orale",
        "Deodoranti-Accessori",
        "Detergenti-Igiene-intima",
        "Shampoo-Acconciatura",
        "Trattamenti-Creme-Protettive",
        "Calze-Collant",
        "Carta-Igienica-Fazzoletti",
        "Incontinenza-Assorbenti",
        "Sanitaria-Parafarmacia",
        "Accessori",
        "Alimentazione"
    ]
}