// foodEmojis.ts

export const foodEmojisEnglish: Record<string, string> = {
    // Fruits
    apple: "🍎",
    banana: "🍌",
    cherries: "🍒",
    grapes: "🍇",
    lemon: "🍋",
    mango: "🥭",
    orange: "🍊",
    peach: "🍑",
    pear: "🍐",
    pineapple: "🍍",
    strawberry: "🍓",
    watermelon: "🍉",
    avocado: "🥑",
    blueberry: "🫐",

    // Vegetables
    broccoli: "🥦",
    carrot: "🥕",
    corn: "🌽",
    cucumber: "🥒",
    garlic: "🧄",
    lettuce: "🥬",
    mushroom: "🍄",
    onion: "🧅",
    potato: "🥔",
    pumpkin: "🎃",
    spinach: "🥬",
    tomato: "🍅",
    zucchini: "🥒",

    // Meat and Fish
    bacon: "🥓",
    beef: "🥩",
    chicken: "🍗",
    egg: "🥚",
    fish: "🐟",
    lobster: "🦞",
    salmon: "🍣",
    shrimp: "🍤",
    steak: "🥩",
    sushi: "🍣",
    turkey: "🦃",

    // Dairy and Eggs
    butter: "🧈",
    cheese: "🧀",
    milk: "🥛",
    yogurt: "🫙",

    // Desserts and Snacks
    cake: "🍰",
    chocolate: "🍫",
    cookie: "🍪",
    croissant: "🥐",
    donut: "🍩",
    ice_cream: "🍨",
    pie: "🥧",
    popcorn: "🍿",
    pudding: "🍮",
    waffle: "🧇",

    // Italian Foods
    pizza: "🍕",
    pasta: "🍝",
    spaghetti: "🍝",
    lasagna: "🍲",
    risotto: "🍲",
    tiramisu: "🍮",
    focaccia: "🍞",

    // Drinks
    beer: "🍺",
    champagne: "🍾",
    coffee: "☕",
    tea: "🍵",
    wine: "🍷",
    water: "💧",
    juice: "🧃",
    smoothie: "🍹",

    // Other
    bread: "🍞",
    burger: "🍔",
    burrito: "🌯",
    dumpling: "🥟",
    falafel: "🧆",
    fries: "🍟",
    hotdog: "🌭",
    kebab: "🥙",
    ramen: "🍜",
    sandwich: "🥪",
    taco: "🌮",
    toast: "🍞",
    soup: "🥣",
};

// Mappa in italiano
export const foodEmojisItalian: Record<string, string> = {
    // Frutta
    mela: "🍎",
    mele: "🍎",
    banana: "🍌",
    banane: "🍌",
    ciliegia: "🍒",
    ciliegie: "🍒",
    uva: "🍇",
    limone: "🍋",
    limoni: "🍋",
    mango: "🥭",
    manghi: "🥭",
    arancia: "🍊",
    arance: "🍊",
    pesca: "🍑",
    pesche: "🍑",
    pera: "🍐",
    pere: "🍐",
    ananas: "🍍",
    fragola: "🍓",
    fragole: "🍓",
    anguria: "🍉",
    angurie: "🍉",
    avocado: "🥑",
    avocadi: "🥑",
    mirtillo: "🫐",
    mirtilli: "🫐",
    fico: "🍈",
    fichi: "🍈",
    melograno: "🍈",
    melograni: "🍈",

    // Verdura
    broccoli: "🥦",
    broccolo: "🥦",
    carota: "🥕",
    carote: "🥕",
    mais: "🌽",
    cetriolo: "🥒",
    cetrioli: "🥒",
    aglio: "🧄",
    lattuga: "🥬",
    lattughe: "🥬",
    fungo: "🍄",
    funghi: "🍄",
    cipolla: "🧅",
    cipolle: "🧅",
    patata: "🥔",
    patate: "🥔",
    zucca: "🎃",
    zucche: "🎃",
    spinacio: "🥬",
    spinaci: "🥬",
    pomodoro: "🍅",
    pomodori: "🍅",
    zucchina: "🥒",
    zucchine: "🥒",
    cavolo: "🥬",
    cavoli: "🥬",
    peperone: "🫑",
    peperoni: "🫑",

    // Carne e Pesce
    pancetta: "🥓",
    manzo: "🥩",
    pollo: "🍗",
    polli: "🍗",
    uovo: "🥚",
    uova: "🥚",
    pesce: "🐟",
    pesci: "🐟",
    aragosta: "🦞",
    aragoste: "🦞",
    salmone: "🍣",
    salmoni: "🍣",
    gambero: "🍤",
    gamberi: "🍤",
    bistecca: "🥩",
    bistecche: "🥩",
    sushi: "🍣",
    tacchino: "🦃",
    tacchini: "🦃",
    prosciutto: "🍖",
    prosciutti: "🍖",

    // Latticini e Uova
    burro: "🧈",
    formaggio: "🧀",
    formaggi: "🧀",
    latte: "🥛",
    yogurt: "🫙",

    // Dolci e Snack
    torta: "🍰",
    torte: "🍰",
    cioccolato: "🍫",
    biscotto: "🍪",
    biscotti: "🍪",
    croissant: "🥐",
    croissant_plural: "🥐",
    ciambella: "🍩",
    ciambelle: "🍩",
    gelato: "🍨",
    gelati: "🍨",
    crostata: "🥧",
    crostate: "🥧",
    popcorn: "🍿",
    budino: "🍮",
    budini: "🍮",
    waffle: "🧇",
    waffle_plural: "🧇",

    // Cibi Italiani
    pizza: "🍕",
    pizze: "🍕",
    pasta: "🍝",
    spaghetti: "🍝",
    lasagna: "🍲",
    lasagne: "🍲",
    risotto: "🍲",
    tiramisu: "🍮",
    focaccia: "🍞",
    focacce: "🍞",
    gnocchi: "🥔",

    // Bevande
    birra: "🍺",
    birre: "🍺",
    champagne: "🍾",
    caffè: "☕",
    tè: "🍵",
    vino: "🍷",
    vini: "🍷",
    acqua: "💧",
    succhi: "🧃",
    succo: "🧃",
    frullato: "🍹",
    frullati: "🍹",

    // Altro
    pane: "🍞",
    hamburger: "🍔",
    hamburger_plural: "🍔",
    burrito: "🌯",
    burriti: "🌯",
    raviolo: "🥟",
    ravioli: "🥟",
    falafel: "🧆",
    falafel_plural: "🧆",
    patatina: "🍟",
    patatine: "🍟",
    hotdog: "🌭",
    hotdog_plural: "🌭",
    kebab: "🥙",
    kebab_plural: "🥙",
    ramen: "🍜",
    panino: "🥪",
    panini: "🥪",
    taco: "🌮",
    tacos: "🌮",
    toast: "🍞",
    toast_plural: "🍞",
    zuppa: "🥣",
    zuppe: "🥣",
};
