# for local development and testing of tls
tls:
  certificates:
    - certFile: "/var/traefik/certs/local-cert.pem"
      keyFile: "/var/traefik/certs/local-key.pem"

http:
  routers:
    t0-traefik:
      rule: "Host(`traefik.docker.localhost`) && PathPrefix(`/`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
      entryPoints:
        - websecure
    to-web-client:
      rule: "Host(`docker.localhost`) && PathPrefix(`/`)"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
      # for prod
      # tls:
        # certResolver: staging
      service: web-client
      priority: 1000
      entryPoints:
        # - web
        # (optional) Permanent Redirect to HTTPS
        - websecure

  services:
    web-client:
      loadBalancer:
        servers:
          - url: "http://web-client:3000"
