apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraping-conad
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraping-conad
            image: ghcr.io/fchieric/scraping-service-conad:latest
          restartPolicy: OnFailure
