apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraping-gros-group
spec:
  schedule: "0 0 */14 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraping-gros-group
            image: ghcr.io/fchieric/scraping-service-gros-group:latest
          restartPolicy: OnFailure
