ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.15.3}

# COPY config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
# COPY setup-elasticsearch.sh /usr/share/elasticsearch/setup-elasticsearch.sh
# RUN chmod +x /usr/share/elasticsearch/setup-elasticsearch.sh
# ENTRYPOINT ["/usr/share/elasticsearch/setup-elasticsearch.sh"]



# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
